### ISSUE TITLE
Collisions

### ISSUE THREAD

**Issue by jrabasco** [BinaryBrain/Elodie-Dream#12]
Due to the recent modification of the way the speed is set (it now takes into account the framerate), the collisions seem buggy on computer with low framerate.

Please Gerardufoin contact me (@Rabyss) I'll be glad to work on it with you !

**Comment by Gerardufoin** [comment]
Already told you. It's not the collisions who are at cause, it's the way we use them in the doStuff. It's BinaryBrain who redid the doStuff of Elodie

**Comment by BinaryBrain** [comment]
I still think it's the collisions who are in cause. I used it exactly as you did.
The problem is you don't check collision that will happend during the next frame (using the speed vector) as I told you.

**Comment by Gerardufoin** [comment]
I check one pixel ahead. If there will be a collision, it's reported. The collisions work.

**Comment by Gerardufoin** [comment]
And I already told you. What was in the doStuff was crap. If you did the same, then no wonder it doesn't work.

**Comment by Gerardufoin** [comment]
Ok, I took some time to reflect on this (not really the time but well) and I understand what you wanted to say. I'll change the collision when I go back home.
(And now I have to work, so I won't reply about the game until tonight)
