### ISSUE TITLE
Images/Sprites à faire

### ISSUE THREAD

**Issue by Protectator** [BinaryBrain/Elodie-Dream#18]
Si vous voulez faire un de ces trucs et que ca semble dans vos cordes, alors allez-y ! Et cochez la case pour montrer que qqun bosse dessus :
## Fucking URGENT et indispensable
- [x] Ennemi : Squelette OU Armure vivante OU Fantôme OU Zombie OU (autre idée de monstre pour un château hanté que vous avez envie) @Tellendil
- [x] Ennemi : Phacochère de Sejuani OU Yeti OU Poro ninja (?) OU (autre idée de monstre pour un monde glacé que vous avez envie)
- [x] Fin du level: portail (@Flagoul)
## Indispensable
- [ ] Ennemi : Petit phénix OU Golem d'Obsidienne OU Salamèche OU (autre idée de monstre pour un volcan que vous avez envie) (@Tellendil)
- [x] Ecran titre
  (@BinaryBrain)
- [x] Ecran de Game Over
  (@Flagoul)
- [x] Animation d'Attaque de Elodie
  (@Gerardufoin)
## Pas indispensable mais cool quand même
- [ ] Des autres ennemis, whatever lesquels
- [ ] Animation de mort de Elodie
- [ ] D'autres poros (avec des accessoires, etc)
- [ ] Bouton de sélection de menu
- [ ] Des glaçons qui volent sur Freljord

(Et rajoutez des trucs à la liste si ca manque !)

**Comment by BasileVu** [comment]
Je peux m'occuper de l'écran du Game over.

**Comment by BinaryBrain** [comment]
> Animation de mort de Elodie

En même temps, le "Dream Over" pop à la frame ou elle à plus de vie.
