### ISSUE TITLE
The second ice level is impossible

### ISSUE THREAD

**Issue by SolalPirelli** [BinaryBrain/Elodie-Dream#22]
The only way to jump above the first big pit (where there's a Sprite before you jump) is to use the corner-jumping bug.

**Comment by Protectator** [comment]
It's not a bug, it's a feature. :)

**Comment by SolalPirelli** [comment]
STFU

**Comment by BinaryBrain** [comment]
It's clearly not a bug. You can finish the level just by blocking yourself behind a tile.
