### ISSUE TITLE
Find a solution to update from v1.0 to v1.1 easily

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/Elodie-Dream#32]
We should find a user-friendly solution for players to update from v1.0 to v1.1 while keeping saves.
Any ideas?

**Comment by BasileVu** [comment]
Theorically the saves from 1.1 are the same as in 1.0 except they contain the scores (which weren't kept in the 1.0 anyway), so there shouldn't be any problem.

**Comment by BasileVu** [comment]
Tested it, everything should be ok.
