### ISSUE TITLE
v1.1 New levels

### ISSUE THREAD

**Issue by Protectator** [BinaryBrain/Elodie-Dream#36]
Do you have some ideas about how many maps will we add, how we will introduce them and where in the game ?

About the theme, I have some inspiration for a futuristic level for example (lasers, holographs, the matrix etc) as we don't have anything that resembles it actually, but I'm looking for some other ideas, so share what you think !

**Comment by BinaryBrain** [comment]
I also had the idea of a futuristic theme. Maybe with cell shading graphics or something that looks more vectorial.

**Comment by jrabasco** [comment]
### New ennemies

Modern:
- Birds (crows)
- Red light

Space: 
- Meteorite
- Alien/Satellite/Whatever
- Laser
