### ISSUE TITLE
Linux Version

### ISSUE THREAD

**Issue by jrabasco** [BinaryBrain/Elodie-Dream#40]
I tried compiling the project by generating a makefile with cbp2make (http://sourceforge.net/projects/cbp2make/).

It should work if we adjust the following things :
- Recode FileHandler.cpp so that it uses linux functions instead of the ones from windows.h
- Change the way we handle the icon to a linux way of handling it (without windres)
- Maybe some naming adjustment (mainly capital vs non capital letters in the file names)

I put this issue in the Version 1.1 milestone because I think this should not take long but we can still not do it.

**Comment by BasileVu** [comment]
cbc7c50653c7e90621462116495d21f413dd2b90: FileHandler doesn't use window.h anymore.
It works fine on windows but I still have to try it on linux.

**Comment by BasileVu** [comment]
Just tried it, everything seems to work for me now (except for the performances, but I think it's because I run it on a VM).

**Comment by jrabasco** [comment]
We will test it further. One way to distribute it would be to build a package for the project so that people can build it with their package manager.

**Comment by jrabasco** [comment]
Seems to run well on my Aspire One, even though a bit slow sometimes (mainly because of the poor performances of the PC used). We could move one step forward if we could build the above mentioned package.

**Comment by jrabasco** [comment]
The project can compile on linux as long as there is an sfml version for the distribution.
