### ISSUE TITLE
Jump Control

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/Elodie-Dream#41]
I've asked a bunch of my friends what's the worst point in our game.
One of the most recurrent answer was that the jump is uncontrollable, therefore unpredictable, therefore terrible.

I didn't remember why do we choose to have a fixed jump, if we talked about it.

One of the best and simpler solution to this is to lower the gravity when Elodie's is jumping and the jump key (space bar) is still down. When the player release the key, the gravity is reset to it's default value and everything's good.

A lot of video games do this. From Super Mario to Robot Unicorn Attack. A friend also pointed that the game having an auto-run makes it even harder than in other games.

**Comment by Protectator** [comment]
I agree that controlling the distance of the jump would be easier. Not sure if it's a good idea for the difficulty of the game tho.
But a fixed jump IS predictable.
And we didn't really talk about controlling the height of the jump. Everyone just assumed a jump would always jump the same height.

**Comment by jrabasco** [comment]
Interesting point of view. Worth giving it a look.

**Comment by jrabasco** [comment]
This was abandoned I guess, feel free to reopen the issue if you want to try it. I am closing it in order to complete the milestone (should have been done weeks ago).
