### ISSUE TITLE
How do we kill enemies ?

### ISSUE THREAD

**Issue by Protectator** [BinaryBrain/Elodie-Dream#5]
I mean, what is the PRIMARY method to kill enemies, what is the first one that needs to be implemented ?
- Jumping on them ?
- Striking with a weapon ?
- Using spells ?

(fun fact : every answer raises a few more questions :D)

**Comment by Gerardufoin** [comment]
STRIKE 'EM WITH YOUR D...
I think striking them with a weapon would be the best. I'm not really fan of the "jump on their head" thing if you have a weapon (the weapon kinda lost of its value... But it's my opinion)

**Comment by Protectator** [comment]
That's my opinion too. So let's assume jumping on them doesn't kill and we have to use a weapon, something like a sword at start.

**Comment by BinaryBrain** [comment]
I think the most basic attack should be a punch à la Vi (in term of power).
If we choose a sword, we have to justify where did she find it.

**Comment by BinaryBrain** [comment]
Or maybe a big wooden stick, but this is not as badass as a punch would be.
